### PR TITLE
Refactoring, cleartype support

### PR DESCRIPTION
**Pull request by Sidneys1**

### CODE REVIEW

**Comment by Donkie** [comment]
I don't know what to say, thanks for the commitment!

Ready to merge?

**Comment by Sidneys1** [comment]
Should be 100% ready to go. Though you might not want to manually edit the solution file and change the VS version back, I was using vs2015 :fearful:

**Comment by Donkie** [comment]
The new font looks amazing, good job on that. I'm not too fond of the underscore variables though, can you perhaps fix that? (I only got an express VS so I can't install any plugins.. :( )

**Comment by Sidneys1** [comment]
You could just do find and replace '_' to ' '. 😊 Sorry, forgot I had resharper renaming on

Sent from my Windows Phone

**Pull request merged**
